title: Jekyll.Pizza blog
email: jekylldotpizza@gmail.com
description: A blog documenting the creation of Jekyll.Pizza, a Jekyll blog generator
baseurl: ''
url: trevormast.github.io
twitter_username: jekyllpizza
github_username: trevormast
markdown: kramdown
theme: clean-jekyll
